### ISSUE TITLE
NTSC shaders produce black screen.

### ISSUE THREAD

**Issue by Nobody1707** [hizzlekizzle/quark-shaders#1]
The NTSC, Integrated Television, Motion Blur Exponential Decay, and cgwg-CRT-reconstructed shaders produce nothing but a black screen.

Higan 0.94, Win7, AMD Radeon 6630m 256mb, Catalyst version 14.3, OpenGL version 6.14.10.12798

**Comment by hizzlekizzle** [comment]
Oh hey, just saw this issue. Yeah, there was a change to higan's shader system that seems to have broken a bunch of them like that. I'll see what I can do to make them work with v094.

**Comment by Oskenso** [comment]
This is now fixed in 76677de89d7dd78869f59d47e45d9aa2f317b6e9
