### ISSUE TITLE
Downsample recommended 50% width is not compatible with SNES pseudo-hires mode

### ISSUE THREAD

**Issue by PeterSamuels** [hizzlekizzle/quark-shaders#10]
The downsample.fs file recommends 
`program`
`   filter: nearest`
`   fragment: downsample.fs`
`   height: 50%`
`   width: 50%`

However, the 50% width does not work properly with games like Kirby's Dream Land 3 and Trials of Mana which use pseudo-hires mode. If you set the width to 100% it works better, but it is slightly wider for some reason. If you have width at 100% and remove the `fragment: downsample.fs` line, it works perfectly, so I don't think the downsample.fs is even needed.

**Comment by hizzlekizzle** [comment]
Correct, it's not needed for those games, and those games are exactly why it's needed at all. That is, higan/ares/et al support doing changes to resolution mid-frame, which means they have to draw the largest possible width at all times, even though most of the time it's not needed.

**Comment by PeterSamuels** [comment]
These games are 512*224 (240p).
