### ISSUE TITLE
How do you get these to show up in Higan?

### ISSUE THREAD

**Issue by shadelegend333** [hizzlekizzle/quark-shaders#3]
Tried messing with the bml file and everything, nothing shows up...

**Comment by hizzlekizzle** [comment]
you should be able to take any/all of these *.shader directories and put them inside higan's Video Shaders directory, and then they should show up in the pulldown menu.

**Comment by shadelegend333** [comment]
there is no default shader directory made in latest v100 as far as im aware...

**Comment by hizzlekizzle** [comment]
I haven't messed with v100 but I know byuu didn't ship a Video Shaders folder with it by default. I don't know if you can just make that directory on your own or not. Someone I talked to on IRC said he just reverted back to an earlier version. If that's not an acceptable solution for you, you might try downloading an older version that works with shaders and replacing the executables with the one(s) from v100.

**Comment by shadelegend333** [comment]
I got it working by downloading v094 and overwriting everything except the config files. Thx

**Comment by scnale** [comment]
This is a bit old but I tried putting these shaders in a Video Shaders folder that I created with success. According to the changelogs this should work for v096 and up. I am using v102.
